version: "3.8"

services:
  # Backend service
  backend:
    build: ./backend # Xây dựng từ Dockerfile trong thư mục backend
    ports:
      - "3002:3002" # Ánh xạ cổng 3000 từ container ra máy thật
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskboard # Kết nối tới MongoDB với database tên taskboard
    depends_on:
      - mongo # Đảm bảo MongoDB chạy trước
    volumes:
      - ./backend:/app # Đồng bộ code giữa máy thật và container
      - /app/node_modules # Giữ nguyên node_modules trong container

  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # Ánh xạ cổng 5173
    environment:
      - VITE_API_BASE_URL=http://45.77.172.27:3002 # Địa chỉ backend để frontend gọi API
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend # Đảm bảo backend chạy trước

  # MongoDB service
  mongo:
    image: mongo:6 # Dùng MongoDB phiên bản 6
    ports:
      - "27018:27017" # Ánh xạ cổng MongoDB
    volumes:
      - mongodb_data:/data/db # Lưu dữ liệu database vào volume để không mất khi tắt container

volumes:
  mongodb_data: # Tạo volume lưu dữ liệu MongoDB
